// Code generated by ProtoGen; DO NOT EDIT.

package ws

import "time"

// MessageType represents the type of a WebSocket message
type MessageType string

const (
	TypeEvent    MessageType = "event"
	TypeRequest  MessageType = "request"
	TypeResponse MessageType = "response"
	TypeError    MessageType = "error"
	TypeClose    MessageType = "close"
)

// EventType represents all possible event names
type EventType string

// Client to Server events
const (
	EventAuth        EventType = "auth"
	EventCardDrawReq EventType = "card_draw"
	EventBattle      EventType = "battle_action"
	EventNavigate    EventType = "world_navigate"
	EventSkillUseReq EventType = "skill_use"
	EventItemUseReq  EventType = "item_use"
	EventPing        EventType = "ping"
	EventSync        EventType = "sync"
)

// Server to Client event names
const (
	EventAuthAck          EventType = "auth_ack"
	EventPong             EventType = "pong"
	EventCardDrawResp     EventType = "card_draw"
	EventBattleActionResp EventType = "battle_action"
	EventWorldNavigate   EventType = "world_navigate"
	EventSkillUseResp     EventType = "skill_use"
	EventItemUseResp      EventType = "item_use"
	EventSyncResp         EventType = "sync"

	// Server push events (10 types)
	EventServerCardDraw    EventType = "event_card_draw"
	EventWorldMapUpdate    EventType = "event_world_map_update"
	EventBattleUpdate      EventType = "event_battle_update"
	EventPlayerStatus      EventType = "event_player_status"
	EventSkillCooldown     EventType = "event_skill_cooldown"
	EventDeckExhausted     EventType = "event_deck_exhausted"
	EventItemUsed          EventType = "event_item_used"
	EventEncounter         EventType = "event_encounter"
	EventLevelUp           EventType = "event_level_up"
	EventElementReaction   EventType = "event_element_reaction"
	EventNarrative         EventType = "event_narrative"
)

// ErrorCode represents server error codes
type ErrorCode string

const (
	ErrInvalidToken        ErrorCode = "INVALID_TOKEN"
	ErrPlayerNotFound      ErrorCode = "PLAYER_NOT_FOUND"
	ErrDeckNotFound        ErrorCode = "DECK_NOT_FOUND"
	ErrDeckExhausted       ErrorCode = "DECK_EXHAUSTED"
	ErrInsufficientStamina ErrorCode = "INSUFFICIENT_STAMINA"
	ErrInsufficientMP      ErrorCode = "INSUFFICIENT_MP"
	ErrSkillNotLearned     ErrorCode = "SKILL_NOT_LEARNED"
	ErrSkillOnCooldown    ErrorCode = "SKILL_ON_COOLDOWN"
	ErrLocationLocked      ErrorCode = "LOCATION_LOCKED"
	ErrLocationUnreachable ErrorCode = "LOCATION_UNREACHABLE"
	ErrItemNotFound        ErrorCode = "ITEM_NOT_FOUND"
	ErrInvalidAction       ErrorCode = "INVALID_ACTION"
	ErrSessionExpired      ErrorCode = "SESSION_EXPIRED"
	ErrRateLimited         ErrorCode = "RATE_LIMITED"
)

// BaseMessage is the common structure for all WebSocket messages
type BaseMessage struct {
	Type      MessageType `json:"type"`
	Event     EventType   `json:"event"`
	Seq       int64       `json:"seq"`
	Timestamp string     `json:"timestamp"`
	Data      interface{} `json:"data"`
}

// AuthMessage is the client auth payload
type AuthMessage struct {
	PlayerID string `json:"player_id"`
	Token    string `json:"token"`
	DeviceID string `json:"device_id"`
}

// AuthAckData is the auth ack response data
type AuthAckData struct {
	Success    bool   `json:"success"`
	PlayerID   string `json:"player_id,omitempty"`
	SessionID  string `json:"session_id,omitempty"`
	ServerTime string `json:"server_time,omitempty"`
	ErrorCode  string `json:"error_code,omitempty"`
	Message    string `json:"message,omitempty"`
}

// PongData is the pong response data
type PongData struct {
	ServerTime string `json:"server_time"`
	LatencyMs  int64  `json:"latency_ms"`
}

// CardDrawRequest is the card draw request data
type CardDrawRequest struct {
	DeckID        string `json:"deck_id"`
	Count         int    `json:"count"`
	DealerID      string `json:"dealer_id"`
	ForceCardType string `json:"force_card_type"`
}

// CardInfo represents a card
type CardInfo struct {
	ID          string   `json:"id"`
	Type        string   `json:"type"`
	Title       string   `json:"title"`
	Description string   `json:"description,omitempty"`
	Element     string   `json:"element,omitempty"`
	Damage      float64  `json:"damage"`
	MPCost      int      `json:"mp_cost,omitempty"`
	Cooldown    int      `json:"cooldown,omitempty"`
	Effects     []string `json:"effects,omitempty"`
}

// CardDrawResponseData is the card draw response data
type CardDrawResponseData struct {
	Success          bool       `json:"success"`
	DrawnCards       []CardInfo `json:"drawn_cards"`
	NextCardTypeHint string     `json:"next_card_type_hint,omitempty"`
	DeckExhausted    bool       `json:"deck_exhausted"`
	DealerHint       string     `json:"dealer_hint,omitempty"`
	CardsRemaining   int        `json:"cards_remaining"`
}

// BattleActionRequest is the battle action request data
type BattleActionRequest struct {
	PlayerID          string  `json:"player_id"`
	Action            string  `json:"action"` // dodge, block, counter, attack
	AttackTimingMs    int     `json:"attack_timing_ms"`
	ActionTimingMs    int     `json:"action_timing_ms"`
	StaminaAvailable  int     `json:"stamina_available"`
	MPAvailable       int     `json:"mp_available"`
	BaseDamage        float64 `json:"base_damage"`
	Element           string  `json:"element"`
	DefenderElement   string  `json:"defender_element"`
	ElementMastery    int     `json:"element_mastery"`
	DefenderLevel     int     `json:"defender_level"`
	IsCritical        bool    `json:"is_critical"`
	CounterBaseDamage float64 `json:"counter_base_damage"`
}

// BattleActionResponseData is the battle action response data
type BattleActionResponseData struct {
	Action             string      `json:"action"`
	Success            bool        `json:"success"`
	Description        string      `json:"description"`
	DodgeResult        interface{} `json:"dodge_result,omitempty"`
	BlockResult        interface{} `json:"block_result,omitempty"`
	AttackDamage       interface{} `json:"attack_damage,omitempty"`
	SwordIntentGained  int         `json:"sword_intent_gained"`
}

// WorldNavigateRequest is the world navigate request data
type WorldNavigateRequest struct {
	PlayerID         string `json:"player_id"`
	TargetLocationID string `json:"target_location_id"`
	UseOptimalRoute  bool   `json:"use_optimal_route"`
}

// WorldNavigateResponseData is the world navigate response data
type WorldNavigateResponseData struct {
	Success               bool            `json:"success"`
	Message               string          `json:"message"`
	TravelTime            string          `json:"travel_time"`
	Route                 *RouteInfo      `json:"route,omitempty"`
	NewLocation           *LocationInfo   `json:"new_location,omitempty"`
	AvailableDealers      []DealerInfo    `json:"available_dealers,omitempty"`
	EncounterProbability  *EncounterProb  `json:"encounter_probability,omitempty"`
}

// RouteInfo describes a travel route
type RouteInfo struct {
	Path            []LocationSummary `json:"path"`
	TotalDistance   int               `json:"total_distance"`
	Dangers         []string          `json:"dangers"`
}

// LocationSummary is a minimal location description
type LocationSummary struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// LocationInfo is a full location description
type LocationInfo struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	LocationType string `json:"location_type"`
	DangerLevel  int    `json:"danger_level"`
	RegionID     string `json:"region_id,omitempty"`
}

// DealerInfo describes a dealer
type DealerInfo struct {
	ID   string `json:"id"`
	Type string `json:"type"`
	Name string `json:"name"`
}

// EncounterProb describes encounter probabilities
type EncounterProb struct {
	OnRoute        float64 `json:"on_route"`
	AtDestination  float64 `json:"at_destination"`
}

// SkillUseRequest is the skill use request data
type SkillUseRequest struct {
	PlayerID string `json:"player_id"`
	SkillID  string `json:"skill_id"`
	TargetID string `json:"target_id"`
}

// ItemUseRequest is the item use request data
type ItemUseRequest struct {
	PlayerID string `json:"player_id"`
	ItemID   string `json:"item_id"`
	Count    int    `json:"count"`
}

// SyncRequest is the reconnect sync request data
type SyncRequest struct {
	LastSeq  int64  `json:"last_seq"`
	PlayerID string `json:"player_id"`
}

// PlayerStatus represents a player's status
type PlayerStatus struct {
	HP          int     `json:"hp"`
	MaxHP       int     `json:"max_hp"`
	MP          int     `json:"mp"`
	MaxMP       int     `json:"max_mp"`
	Stamina     int     `json:"stamina"`
	MaxStamina  int     `json:"max_stamina"`
	SwordIntent int     `json:"sword_intent"`
	Level       int     `json:"level,omitempty"`
	Exp         int     `json:"exp,omitempty"`
}

// SyncResponseData is the sync response data
type SyncResponseData struct {
	CurrentPlayerStatus *PlayerStatus `json:"current_player_status,omitempty"`
	CurrentLocation    *LocationInfo  `json:"current_location,omitempty"`
	CurrentBattle      interface{}    `json:"current_battle"`
	PendingEvents      []BaseMessage  `json:"pending_events,omitempty"`
}

// ---- Server Push Event Data ----

// EventCardDrawData is for event_card_draw server push
type EventCardDrawData struct {
	PlayerID       string     `json:"player_id"`
	PlayerName     string     `json:"player_name"`
	DealerID       string     `json:"dealer_id"`
	DealerName     string     `json:"dealer_name"`
	DrawnCards     []CardInfo `json:"drawn_cards"`
	CardsRemaining int        `json:"cards_remaining"`
	Narrative      string     `json:"narrative,omitempty"`
}

// EventWorldMapUpdateData is for event_world_map_update
type EventWorldMapUpdateData struct {
	PlayerID                string        `json:"player_id"`
	PreviousLocation        *LocationInfo `json:"previous_location"`
	CurrentLocation         *LocationInfo `json:"current_location"`
	TravelStats             *TravelStats  `json:"travel_stats"`
	VisitedLocationsCount   int           `json:"visited_locations_count"`
	VisitedRegionsCount     int           `json:"visited_regions_count"`
}

// TravelStats describes travel statistics
type TravelStats struct {
	TotalTravels   int    `json:"total_travels"`
	TotalDistance  int    `json:"total_distance"`
	LastTravelAt   string `json:"last_travel_at"`
}

// EventBattleUpdateData is for event_battle_update
type EventBattleUpdateData struct {
	BattleID          string        `json:"battle_id"`
	Turn              int           `json:"turn"`
	ActivePlayerID    string        `json:"active_player_id"`
	EnemyAction       string        `json:"enemy_action"`
	EnemyIntent       string        `json:"enemy_intent"`
	AttackTimingMs    int           `json:"attack_timing_ms"`
	PlayerStatus      *PlayerStatus `json:"player_status"`
	AvailableActions  []string      `json:"available_actions"`
	Message           string        `json:"message"`
}

// EventPlayerStatusData is for event_player_status
type EventPlayerStatusData struct {
	PlayerID      string                 `json:"player_id"`
	Changes       map[string]StatChange  `json:"changes"`
	CurrentStatus *PlayerStatus         `json:"current_status"`
}

// StatChange describes a stat change
type StatChange struct {
	From  interface{} `json:"from"`
	To    interface{} `json:"to"`
	Delta interface{} `json:"delta"`
}

// EventSkillCooldownData is for event_skill_cooldown
type EventSkillCooldownData struct {
	PlayerID                   int  `json:"player_id"`
	SkillID                    string `json:"skill_id"`
	SkillName                  string `json:"skill_name"`
	CooldownRemainingSeconds   int    `json:"cooldown_remaining_seconds"`
	Available                  bool   `json:"available"`
}

// EventDeckExhaustedData is for event_deck_exhausted
type EventDeckExhaustedData struct {
	PlayerID         string `json:"player_id"`
	DeckID           string `json:"deck_id"`
	DeckName         string `json:"deck_name"`
	TotalCardsDrawn  int    `json:"total_cards_drawn"`
	AutoReshuffle    bool   `json:"auto_reshuffle"`
	Message          string `json:"message"`
}

// EventItemUsedData is for event_item_used
type EventItemUsedData struct {
	PlayerID           string      `json:"player_id"`
	ItemID             string      `json:"item_id"`
	ItemName           string      `json:"item_name"`
	Effects            *ItemEffects `json:"effects"`
	CurrentHP          int         `json:"current_hp"`
	ItemCountRemaining int         `json:"item_count_remaining"`
}

// ItemEffects describes item effects
type ItemEffects struct {
	HPRestored float64 `json:"hp_restored"`
	BuffActive bool    `json:"buff_active"`
}

// EventEncounterData is for event_encounter
type EventEncounterData struct {
	PlayerID              string        `json:"player_id"`
	EncounterType         string        `json:"encounter_type"` // enemy, random_event
	Location              *LocationInfo `json:"location"`
	Enemy                 *EnemyInfo    `json:"enemy,omitempty"`
	EncounterProbability  float64       `json:"encounter_probability"`
	Narrative             string        `json:"narrative"`
	BattleID              string        `json:"battle_id"`
}

// EnemyInfo describes an enemy
type EnemyInfo struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Level       int    `json:"level"`
	HP          int    `json:"hp"`
	MaxHP       int    `json:"max_hp"`
	DangerLevel int    `json:"danger_level"`
}

// EventLevelUpData is for event_level_up
type EventLevelUpData struct {
	PlayerID    string                `json:"player_id"`
	FromLevel   int                   `json:"from_level"`
	NewLevel    int                   `json:"new_level"`
	Exp         int                   `json:"exp"`
	ExpNeeded   int                   `json:"exp_needed"`
	StatChanges map[string]StatChange `json:"stat_changes"`
	Message     string                `json:"message"`
}

// EventElementReactionData is for event_element_reaction
type EventElementReactionData struct {
	PlayerID                string  `json:"player_id"`
	AttackerElement         string  `json:"attacker_element"`
	DefenderElement         string  `json:"defender_element"`
	ReactionType            string  `json:"reaction_type"`
	ReactionDamage          float64 `json:"reaction_damage"`
	SuppressionMultiplier   float64 `json:"suppression_multiplier"`
	Description             string  `json:"description"`
}

// EventNarrativeData is for event_narrative
type EventNarrativeData struct {
	TriggerType        string             `json:"trigger_type"`
	PlayerID           string             `json:"player_id"`
	CardID             string             `json:"card_id,omitempty"`
	CardTitle          string             `json:"card_title,omitempty"`
	DealerID           string             `json:"dealer_id,omitempty"`
	Location           string             `json:"location,omitempty"`
	Content            *NarrativeContent  `json:"content"`
	DisplayDurationMs  int                `json:"display_duration_ms"`
}

// NarrativeContent describes narrative content
type NarrativeContent struct {
	Text       string `json:"text"`
	Dialogue   string `json:"dialogue,omitempty"`
	Atmosphere string `json:"atmosphere,omitempty"`
	AudioCue   string `json:"audio_cue,omitempty"`
}

// NowISO returns the current ISO 8601 timestamp in UTC
func NowISO() string {
	return time.Now().UTC().Format("2006-01-02T15:04:05.000Z")
}
